# Generated by Django 3.1.2 on 2020-10-28 11:01

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rdt', '0003_media_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='raw_payload',
            field=jsonfield.fields.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='classifier_results',
            field=jsonfield.fields.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='results',
            field=jsonfield.fields.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='status',
            field=models.CharField(choices=[('COMPLETE', 'COMPLETE'), ('RUNNING', 'RUNNING'), ('BUILDING', 'BUILDING'), ('QUEUED', 'QUEUED')], default='COMPLETE', max_length=10),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='test_profile_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='time_started',
            field=models.DateTimeField(null=True),
        ),
    ]
