# Generated by Django 3.1.2 on 2020-11-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdt', '0004_auto_20201028_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsession',
            name='status',
            field=models.CharField(choices=[('COMPLETE', 'COMPLETE'), ('RUNNING', 'RUNNING'), ('BUILDING', 'BUILDING'), ('QUEUED', 'QUEUED')], default='COMPLETE', max_length=15),
        ),
    ]
