# Generated by Django 3.1.2 on 2020-11-09 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
        ('rdt', '0005_auto_20201105_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='domain.domain'),
            preserve_default=False,
        ),
    ]
