# Generated by Django 3.1.2 on 2020-12-15 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rdt', '0006_testsession_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_list', to='rdt.testsession'),
        ),
    ]
