# Generated by Django 3.1.2 on 2021-01-26 21:34

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rdt', '0007_auto_20201215_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='metrics',
            field=jsonfield.fields.JSONField(blank=True, default=dict, null=True),
        ),
    ]
