# Generated by Django 3.1.2 on 2021-01-26 23:52

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rdt', '0008_testsession_metrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSessionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(null=True)),
                ('tag', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('media_key', models.CharField(blank=True, max_length=255, null=True)),
                ('json', jsonfield.fields.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
    ]
