# Generated by Django 3.1.2 on 2021-01-27 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rdt', '0009_testsessionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsessionlog',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='rdt.testsession'),
            preserve_default=False,
        ),
    ]
