# Generated by Django 3.1.2 on 2021-04-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdt', '0010_testsessionlog_session'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='media',
            constraint=models.UniqueConstraint(fields=('session_id', 'external_id'), name='unique media record'),
        ),
    ]
