# Generated by Django 3.1.2 on 2020-11-28 15:22

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_current_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='config',
            field=jsonfield.fields.JSONField(default=dict, null=True),
        ),
    ]
