# Generated by Django 3.1.2 on 2020-12-15 02:28

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='config',
            field=jsonfield.fields.JSONField(blank=True, default=dict, null=True),
        ),
    ]
